- name: functions
  hosts: local
  connection: local
  vars:
    pesrsons: "ramesh,vamsi,deva,eswar"
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "hello, {{ person | default('ramesh') }}"
    
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{ persons | split(',') }}"
    
