- name: functions
  hosts: local
  connection: local
  vars:
    persons: "ramesh,vamsi,deva,eswar"
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "hello, {{ person | default('ramesh') }}"
    
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{ persons | split(',') }}"

- name: convert map into list
  vars: 
    course:
      name: ansible
      duration: 10hr
      trainer: vamsi
  ansible.builtin.debug:
    msg: "course info: {{ course | dict2items }}"    
    
